# Generated by Django 4.2 on 2026-01-30 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token_encrypted", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=20, unique=True)),
                ("titulo", models.CharField(max_length=300)),
                ("descripcion", models.TextField()),
                ("url_video", models.URLField()),
                ("url_thumbnail", models.URLField()),
                ("canal_id", models.CharField(max_length=50)),
                ("canal_nombre", models.CharField(max_length=200)),
                ("duracion", models.CharField(blank=True, max_length=20)),
                ("fecha_publicacion", models.DateTimeField()),
                ("vistas", models.BigIntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("comentarios", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("programacion", "Programación"),
                            ("bases_datos", "Bases de Datos"),
                            ("redes", "Redes"),
                            ("seguridad", "Seguridad"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("etiquetas", models.CharField(blank=True, max_length=500)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "agregado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Videos",
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("operacion", models.CharField(max_length=50)),
                ("unidades", models.IntegerField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("publica", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(related_name="playlists", to="videos.video"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="quotausage",
            index=models.Index(fields=["fecha"], name="videos_quot_fecha_817ee7_idx"),
        ),
    ]
