"""
Django settings for youtube_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'videos',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "youtube_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "youtube_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',  # Motor MySQL
        'NAME': 'youtube_db',              # Nombre de la base de datos
        'USER': 'root',            # Usuario de MySQL
        'PASSWORD': '12345678',            # Contraseña del usuario
        'HOST': 'localhost',                 # Servidor (local)
        'PORT': '3306',                      # Puerto por defecto de MySQL
        'OPTIONS': {
            'charset': 'utf8mb4',           # Soporte para emojis y caracteres especiales
        }
    }
}

# YouTube Data API v3 - Cuenta Gratuita Personal
YOUTUBE_API_KEY = config('YOUTUBE_API_KEY')
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'

# OAuth 2.0 - Sin restricciones para cuenta personal
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = config('GOOGLE_REDIRECT_URI')

YOUTUBE_SCOPES = [
    'https://www.googleapis.com/auth/youtube',  # Gestión completa
    'https://www.googleapis.com/auth/youtube.upload',  # Subir videos
    'https://www.googleapis.com/auth/youtube.readonly',  # Solo lectura
    'https://www.googleapis.com/auth/yt-analytics.readonly',  # 🆕 Analytics API
]

# GOOGLE_OAUTH = {
#     'CLIENT_ID': config('GOOGLE_CLIENT_ID'),
#     'CLIENT_SECRET': config('GOOGLE_CLIENT_SECRET'),
#     'REDIRECT_URI': config('GOOGLE_REDIRECT_URI'),
#     'SCOPES': [
#         'https://www.googleapis.com/auth/youtube',
#         'https://www.googleapis.com/auth/youtube.upload'
#     ]
# }


# Configuración de cuotas (2026)
YOUTUBE_QUOTA_CONFIG = {
    'daily_limit': 15000,  # Aumentado de 10,000
    'warning_threshold': 12000,  # 80% de la cuota
    'enable_cache': True,  # Cachear búsquedas repetidas
    'cache_ttl': 3600,  # 1 hora
}

# Categorías de YouTube actualizadas 2026
YOUTUBE_CATEGORIES = {
    '1': 'Film & Animation',
    '2': 'Autos & Vehicles',
    '10': 'Music',
    '15': 'Pets & Animals',
    '17': 'Sports',
    '19': 'Travel & Events',
    '20': 'Gaming',
    '22': 'People & Blogs',
    '23': 'Comedy',
    '24': 'Entertainment',
    '25': 'News & Politics',
    '26': 'Howto & Style',
    '27': 'Education',
    '28': 'Science & Technology',
    '29': 'Nonprofits & Activism',
    '44': 'Shorts',  # 🆕 YouTube Shorts 2026
}

# # Validar configuración
# for key, value in GOOGLE_OAUTH.items():
#     if not value:
#         raise ValueError(f"Falta configurar {key} en .env")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'videos:inicio'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
